apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-frontend
  namespace: episode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode1-frontend
  template:
    metadata:
      labels:
        app: episode1-frontend
    spec:
      containers:
      - name: episode1-frontend
        image: wajidali05/episode1-frontend:v1
        ports:
        - containerPort: 80
