apiVersion: v1
kind: Service
metadata:
  name: episode1-frontend
  namespace: episode1
spec:
  selector:
    app: episode1-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
