apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend4
  template:
    metadata:
      labels:
        app: frontend4
    spec:
      containers:
        - name: frontend4
          image: wajidali05/episode4-frontend:v1
          ports:
            - containerPort: 3000
