apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend5
  template:
    metadata:
      labels:
        app: frontend5
    spec:
      containers:
        - name: frontend5
          image: wajidali05/episode5-frontend:v1
          ports:
            - containerPort: 3000
