apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend3
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
        - name: backend3
          image: wajidali05/episode3-backend:v1
          ports:
            - containerPort: 8000
