apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-backend
  namespace: episode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode1-backend
  template:
    metadata:
      labels:
        app: episode1-backend
    spec:
      containers:
      - name: episode1-backend
        image: wajidali05/episode1-backend:v1
        ports:
        - containerPort: 80
