apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1
          image: wajidali05/episode1-backend:v1
          ports:
            - containerPort: 8000
