apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend3
  template:
    metadata:
      labels:
        app: frontend3
    spec:
      containers:
        - name: frontend3
          image: wajidali05/episode3-frontend:v1
          ports:
            - containerPort: 3000
