apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend4
  template:
    metadata:
      labels:
        app: backend4
    spec:
      containers:
        - name: backend4
          image: wajidali05/episode4-backend:v1
          ports:
            - containerPort: 8000
