apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
        - name: frontend2
          image: wajidali05/episode2-frontend:v1
          ports:
            - containerPort: 3000
